import assert from "node:assert/strict";
import test from "node:test";
import {
  buildDocumentGapReportBundle,
  chunkVerbatimReport,
  type DocumentLeafReportRecord,
} from "../src/document-reports.ts";
import { hashJson, sha256 } from "../src/hash.ts";
import type { AtomicRequirementLeaf, DocumentAuditOutput, SectionId } from "../src/types.ts";

function output(sectionId: SectionId, status: DocumentAuditOutput["status"]): DocumentAuditOutput {
  return {
    schemaVersion: "design-validation/document-audit-output/v1",
    sectionId,
    fingerprint: sha256(sectionId),
    status,
    findings: status === "PASS" ? [] : [{
      requirementId: `${sectionId}-DOC-U0001-R001`,
      pageId: null,
      componentId: null,
      status: "MISSING",
      finding: `${sectionId} exact original finding`,
      evidenceRefs: [],
      implementationRefs: [],
      proposedValue: null,
    }],
    publicOutput: { source: sectionId },
  };
}

function leafRecord(runId: string): DocumentLeafReportRecord {
  const leafOutput = output("S01", "DOCUMENT_GAP");
  const leaf: AtomicRequirementLeaf = {
    requirementId: "S01-DOC-U0001-R001",
    stage: "document",
    sectionId: "S01",
    sourceUnitId: "S01-U0001",
    sourcePath: "DESIGN_INDEX_SPECIFICATION.md",
    sourceKind: "section",
    startOffset: 17,
    endOffset: 43,
    startLine: 2,
    endLine: 2,
    statement: "- Exact source requirement",
    sourceHash: sha256("- Exact source requirement\n"),
    fingerprint: sha256("leaf"),
  };
  return {
    leaf,
    requestId: `${runId}:document-audit:S01:S01-DOC-U0001-R001`,
    attemptRequestIds: [`${runId}:document-audit:S01:S01-DOC-U0001-R001`],
    output: leafOutput,
    outputHash: hashJson(leafOutput),
    rawResponseHash: sha256(`raw-${runId}`),
  };
}

test("the combined Stage 1 report embeds every non-PASS Section report byte-for-byte", () => {
  const record = leafRecord("run-test");
  const bundle = buildDocumentGapReportBundle({
    targetId: "gdweb-test",
    triggerPath: "trigger/DESIGN_INDEX_gdweb-test.md",
    runId: "run-test",
    outputs: [output("S01", "DOCUMENT_GAP"), output("S02", "PASS")],
    leafRecords: [record],
  });
  assert.deepEqual(bundle.sectionReports.map((report) => report.sectionId), ["S01"]);
  for (const report of bundle.sectionReports) {
    const begin = `<!-- BEGIN VERBATIM ${report.sectionId} ${report.contentHash} ${report.byteLength} -->\n`;
    const end = `<!-- END VERBATIM ${report.sectionId} -->`;
    const start = bundle.combinedContent.indexOf(begin);
    const finish = bundle.combinedContent.indexOf(end, start);
    assert.notEqual(start, -1);
    assert.notEqual(finish, -1);
    assert.equal(bundle.combinedContent.slice(start + begin.length, finish), report.content);
    assert.equal(sha256(report.content), report.contentHash);
  }
  assert.match(bundle.combinedContent, /- Exact source requirement/);
  assert.match(bundle.combinedContent, /S01 exact original finding/);
  assert.match(bundle.combinedContent, new RegExp(record.leaf.sourceHash));
  assert.match(bundle.combinedContent, /### 명세서 원문/);
  assert.match(bundle.combinedContent, /### 누락 판정 원문/);
  const sourceMarker = `<!-- BEGIN EXACT SPECIFICATION SOURCE ${record.leaf.requirementId} ${sha256(record.leaf.statement)} -->\n`;
  const sourceEnd = `\n<!-- END EXACT SPECIFICATION SOURCE ${record.leaf.requirementId} -->`;
  const sourceStart = bundle.combinedContent.indexOf(sourceMarker);
  assert.notEqual(sourceStart, -1);
  assert.equal(
    bundle.combinedContent.slice(sourceStart + sourceMarker.length, bundle.combinedContent.indexOf(sourceEnd, sourceStart)),
    record.leaf.statement,
  );
  const finding = record.output.findings[0].finding;
  const findingMarker = `<!-- BEGIN EXACT GAP FINDING ${record.leaf.requirementId} ${sha256(finding)} -->\n`;
  const findingEnd = `\n<!-- END EXACT GAP FINDING ${record.leaf.requirementId} -->`;
  const findingStart = bundle.combinedContent.indexOf(findingMarker);
  assert.notEqual(findingStart, -1);
  assert.equal(
    bundle.combinedContent.slice(findingStart + findingMarker.length, bundle.combinedContent.indexOf(findingEnd, findingStart)),
    finding,
  );
  assert.doesNotMatch(bundle.combinedContent, /run-test:document-audit/);
  assert.doesNotMatch(bundle.combinedContent, /```json/);
  assert.doesNotMatch(bundle.combinedContent, /"schemaVersion"/);
  assert.doesNotMatch(bundle.combinedContent, /Verbatim normalized Section output/);
  assert.doesNotMatch(bundle.combinedContent, /normalized leaf records/i);
  assert.doesNotMatch(bundle.manifestContent, /[{}\[\]"]/);
  assert.match(bundle.manifestContent, /\| S01 \| DOCUMENT_GAP \| 1 \|/);
  assert.doesNotMatch(bundle.combinedContent, /summary generated by/i);
});

test("the plain-text report maps normalized aggregate findings back to their immutable source leaves", () => {
  const record = leafRecord("run-normalized-id");
  record.output.findings[0].requirementId = "S01-DOC-U00C-U0001-R001";
  const aggregate = output("S01", "DOCUMENT_GAP");
  aggregate.findings = [
    {
      ...aggregate.findings[0],
      requirementId: record.leaf.requirementId,
      finding: "First normalized aggregate finding",
    },
    {
      ...aggregate.findings[0],
      requirementId: `${record.leaf.requirementId}-02`,
      finding: "Second normalized aggregate finding",
    },
  ];
  const bundle = buildDocumentGapReportBundle({
    targetId: "gdweb-normalized-id",
    triggerPath: "trigger/DESIGN_INDEX_gdweb-normalized-id.md",
    runId: "run-normalized-id",
    outputs: [aggregate],
    leafRecords: [record],
  });

  assert.match(bundle.combinedContent, /First normalized aggregate finding/);
  assert.match(bundle.combinedContent, /Second normalized aggregate finding/);
  assert.equal(
    bundle.combinedContent.match(/- Exact source requirement/g)?.length,
    2,
  );
  assert.doesNotMatch(bundle.combinedContent, /S01-DOC-U00C-U0001-R001/);
  assert.doesNotMatch(bundle.combinedContent, /```json/);
});

test("GitHub comment chunks reassemble to the exact consolidated report", () => {
  const source = "한글과 exact bytes\n".repeat(40);
  const chunks = chunkVerbatimReport(source, 73);
  assert.ok(chunks.length > 1);
  assert.equal(chunks.map((chunk) => chunk.content).join(""), source);
  assert.ok(chunks.every((chunk) => chunk.byteLength <= 73));
  assert.ok(chunks.every((chunk) => sha256(chunk.content) === chunk.contentHash));
});

test("the same validated findings produce the same report hash across workflow runs", () => {
  const first = buildDocumentGapReportBundle({
    targetId: "gdweb-test",
    triggerPath: "trigger/DESIGN_INDEX_gdweb-test.md",
    runId: "run-one",
    outputs: [output("S01", "DOCUMENT_GAP")],
    leafRecords: [leafRecord("run-one")],
  });
  const second = buildDocumentGapReportBundle({
    targetId: "gdweb-test",
    triggerPath: "trigger/DESIGN_INDEX_gdweb-test.md",
    runId: "run-two",
    outputs: [output("S01", "DOCUMENT_GAP")],
    leafRecords: [leafRecord("run-two")],
  });
  assert.equal(first.combinedHash, second.combinedHash);
  assert.equal(first.combinedContent, second.combinedContent);
  assert.deepEqual(first.manifest, second.manifest);
});
