import assert from "node:assert/strict";
import test from "node:test";
import {
  buildDocumentGapReportBundle,
  chunkVerbatimReport,
} from "../src/document-reports.ts";
import { hashJson, sha256 } from "../src/hash.ts";
import type { AtomicRequirementLeaf, DocumentAuditOutput, SectionId } from "../src/types.ts";

function output(sectionId: SectionId, status: DocumentAuditOutput["status"]): DocumentAuditOutput {
  return {
    schemaVersion: "design-validation/document-audit-output/v1",
    sectionId,
    fingerprint: sha256(sectionId),
    status,
    findings: status === "PASS" ? [] : [{
      requirementId: `${sectionId}-DOC-U0001-R001`,
      pageId: null,
      componentId: null,
      status: "MISSING",
      finding: `${sectionId} exact original finding`,
      evidenceRefs: [],
      implementationRefs: [],
      proposedValue: null,
    }],
    publicOutput: { source: sectionId },
  };
}

test("the combined Stage 1 report embeds every non-PASS Section report byte-for-byte", () => {
  const leaf: AtomicRequirementLeaf = {
    requirementId: "S01-DOC-U0002-R001",
    stage: "document",
    sectionId: "S01",
    sourceUnitId: "S01-U0002",
    sourcePath: "DESIGN_INDEX_SPECIFICATION.md",
    sourceKind: "section",
    startOffset: 17,
    endOffset: 39,
    startLine: 2,
    endLine: 2,
    statement: "Exact source requirement",
    sourceHash: sha256("Exact source requirement\n"),
    fingerprint: sha256("leaf"),
  };
  const leafOutput = output("S01", "DOCUMENT_GAP");
  const bundle = buildDocumentGapReportBundle({
    targetId: "gdweb-test",
    triggerPath: "trigger/DESIGN_INDEX_gdweb-test.md",
    runId: "run-test",
    outputs: [output("S01", "DOCUMENT_GAP"), output("S02", "PASS"), output("S03", "UNKNOWN")],
    leafRecords: [{
      leaf,
      requestId: "run-test:document-audit:S01:S01-DOC-U0002-R001",
      attemptRequestIds: ["run-test:document-audit:S01:S01-DOC-U0002-R001"],
      output: leafOutput,
      outputHash: hashJson(leafOutput),
      rawResponseHash: sha256("raw"),
    }],
  });
  assert.deepEqual(bundle.sectionReports.map((report) => report.sectionId), ["S01", "S03"]);
  for (const report of bundle.sectionReports) {
    const begin = `<!-- BEGIN VERBATIM ${report.sectionId} ${report.contentHash} ${report.byteLength} -->\n`;
    const end = `<!-- END VERBATIM ${report.sectionId} -->`;
    const start = bundle.combinedContent.indexOf(begin);
    const finish = bundle.combinedContent.indexOf(end, start);
    assert.notEqual(start, -1);
    assert.notEqual(finish, -1);
    assert.equal(bundle.combinedContent.slice(start + begin.length, finish), report.content);
    assert.equal(sha256(report.content), report.contentHash);
  }
  assert.match(bundle.combinedContent, /run-test:document-audit:S01:S01-DOC-U0002-R001/);
  assert.match(bundle.combinedContent, /Exact source requirement/);
  assert.match(bundle.combinedContent, new RegExp(leaf.sourceHash));
  assert.doesNotMatch(bundle.combinedContent, /summary generated by/i);
});

test("GitHub comment chunks reassemble to the exact consolidated report", () => {
  const source = "한글과 exact bytes\n".repeat(40);
  const chunks = chunkVerbatimReport(source, 73);
  assert.ok(chunks.length > 1);
  assert.equal(chunks.map((chunk) => chunk.content).join(""), source);
  assert.ok(chunks.every((chunk) => chunk.byteLength <= 73));
  assert.ok(chunks.every((chunk) => sha256(chunk.content) === chunk.contentHash));
});

test("the same validated findings produce the same report hash across workflow runs", () => {
  const first = buildDocumentGapReportBundle({
    targetId: "gdweb-test",
    triggerPath: "trigger/DESIGN_INDEX_gdweb-test.md",
    runId: "run-one",
    outputs: [output("S01", "DOCUMENT_GAP")],
  });
  const second = buildDocumentGapReportBundle({
    targetId: "gdweb-test",
    triggerPath: "trigger/DESIGN_INDEX_gdweb-test.md",
    runId: "run-two",
    outputs: [output("S01", "DOCUMENT_GAP")],
  });
  assert.equal(first.combinedHash, second.combinedHash);
  assert.equal(first.combinedContent, second.combinedContent);
  assert.deepEqual(first.manifest, second.manifest);
});
